changesetBaseRefs: origin/main

changesetIgnorePatterns:
  - .yarn/cache/**

enableImmutableCache: false

enableImmutableInstalls: false

enableNetwork: true

nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.2.3.cjs

defaultSemverRangePrefix: ""

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32
