changesetBaseRefs: origin/main

changesetIgnorePatterns:
  - .yarn/cache/**

defaultSemverRangePrefix: ""

enableImmutableCache: false

enableImmutableInstalls: false

enableNetwork: true

nodeLinker: pnp

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-3.2.3.cjs
