name: Check PR title
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        with:
          requireScope: true
          types: |
            feat
            infra
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
